### ISSUE TITLE
Console Error, No language documents

### ISSUE THREAD

**Issue by TheTechnologyStudio** [MinevoltRPG/Trails#27]
`[21:52:15] [Server thread/INFO]: [Trails] Loading Trails v1.4
[21:52:15] [Server thread/INFO]: [Trails] added: Link material = DIRT_PATH wear = 10 chance = 100 percent
[21:52:15] [Server thread/INFO]: [Trails] added: Link material = COARSE_DIRT wear = 7 chance = 30 percent
[21:52:15] [Server thread/INFO]: [Trails] added: Link material = DIRT wear = 5 chance = 100 percent
[21:52:15] [Server thread/INFO]: [Trails] added: Link material = GRASS_BLOCK wear = 5 chance = 100 percent
[21:52:15] [Server thread/INFO]: [Trails] added: Link material = SANDSTONE wear = 5 chance = 30 percent
[21:52:15] [Server thread/INFO]: [Trails] added: Link material = SAND wear = 5 chance = 100 percent
[21:52:15] [Server thread/INFO]: [Trails] Saving default language files...
[21:52:15] [Server thread/WARN]: java.nio.file.NoSuchFileException: C:\Users\chris\Desktop\MCSERVER%201%20&%202\servers\Zombies%20Factions%20Survival\plugins\Trails-1.4.jar
[21:52:15] [Server thread/WARN]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[21:52:15] [Server thread/WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[21:52:15] [Server thread/WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[21:52:15] [Server thread/WARN]: 	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
[21:52:15] [Server thread/WARN]: 	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
[21:52:15] [Server thread/WARN]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
[21:52:15] [Server thread/WARN]: 	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
[21:52:15] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
[21:52:15] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
[21:52:15] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
[21:52:15] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
[21:52:15] [Server thread/WARN]: 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
[21:52:15] [Server thread/WARN]: 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:318)
[21:52:15] [Server thread/WARN]: 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:257)
[21:52:15] [Server thread/WARN]: 	at Trails-1.4.jar//me.ccrama.Trails.util.ResourceUtils.listFiles(ResourceUtils.java:35)
[21:52:15] [Server thread/WARN]: 	at Trails-1.4.jar//me.ccrama.Trails.configs.Language.saveDefaultLanguageFile(Language.java:77)
[21:52:15] [Server thread/WARN]: 	at Trails-1.4.jar//me.ccrama.Trails.configs.Language.initLanguageFile(Language.java:62)
[21:52:15] [Server thread/WARN]: 	at Trails-1.4.jar//me.ccrama.Trails.configs.Language.<init>(Language.java:58)
[21:52:15] [Server thread/WARN]: 	at Trails-1.4.jar//me.ccrama.Trails.Trails.onLoad(Trails.java:149)
[21:52:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:431)
[21:52:15] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:281)
[21:52:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1105)
[21:52:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:308)
[21:52:15] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[21:52:15] [Server thread/INFO]: [Trails] Cannot find en-US.yml
[21:52:15] [Server thread/INFO]: [Trails] Check Trails/lang/ folder and make sure that
[21:52:15] [Server thread/INFO]: [Trails] you have a filename in that folder that matches
[21:52:15] [Server thread/INFO]: [Trails] Language setting in config.yml
[21:52:15] [Server thread/INFO]: ==+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++==
[21:52:15] [Server thread/INFO]: ++ [Trails] hooked into worldguard! Flag trails-flag registered. Set trails-flag = DENY to deny trails in regions.
[21:52:15] [Server thread/INFO]: ==+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++==
` 

EN_US not generating.

**Comment by alexey-va** [comment]
Send your config.yml please

**Comment by alexey-va** [comment]
Try a new beta release https://github.com/MinevoltRPG/Trails/releases/tag/1.5b
Refactored file copying system a bit

**Comment by DrkMatr1984** [comment]
Yeah, this looks like it may be connected to windows in particular. I only ever tested this on Linux. Definitely needs a refactoring.

**Comment by alexey-va** [comment]
But I also tested it on Windows... By the way, check out Reflections library if you ever would need to list all files in a jar, it is super useful

**Comment by DrkMatr1984** [comment]
I was looking at your changes and it seems very useful, especially in these kinds of use cases. It should make it completely platform and java version independent since you shade in the lib.

**Comment by alexey-va** [comment]
May be fixed in the latest update
